(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> contains() takes at least 3 arguments (4 given)"
p3
sS'layer'
p4
S'/Users/bola/Desktop/web2py/applications/buysellapp/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x1113ed630, file "/Users/bola/Desktop/web2py/applications/buysellapp/controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/bola/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/Users/bola/Desktop/web2py/applications/buysellapp/controllers/default.py", line 97, in <module>\n  File "/Users/bola/Desktop/web2py/gluon/globals.py", line 421, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/bola/Desktop/web2py/applications/buysellapp/controllers/default.py", line 65, in search\n    ads = db(query).select(orderby=db.ads.title)\n  File "/Users/bola/Desktop/web2py/gluon/packages/dal/pydal/objects.py", line 2277, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/Users/bola/Desktop/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/Users/bola/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 758, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/Users/bola/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 673, in _select_wcols\n    query = self.expand(query, query_env=query_env)\n  File "/Users/bola/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 437, in _expand\n    rv = op(first, **optional_args)\nTypeError: contains() takes at least 3 arguments (4 given)\n'
p11
s.